### ISSUE TITLE
I am facing the following problem during triangulation

### ISSUE THREAD

**Issue by wyclearnpy** [talmolab/sleap-anipose#53]
I used the data in tests to conduct experiments. The camera calibration process could proceed, but errors occurred in the triangulation part. Below is the terminal print information.
Traceback (most recent call last):
  File "D:\anaconda\envs\sleap-anipose1\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\anaconda\envs\sleap-anipose1\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\anaconda\envs\sleap-anipose1\Scripts\slap-triangulate.exe\__main__.py", line 7, in <module>
  File "D:\anaconda\envs\sleap-anipose1\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "D:\anaconda\envs\sleap-anipose1\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "D:\anaconda\envs\sleap-anipose1\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\anaconda\envs\sleap-anipose1\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "D:\anaconda\envs\sleap-anipose1\lib\site-packages\sleap_anipose\triangulation.py", line 356, in triangulate_cli
    return triangulate(
  File "D:\anaconda\envs\sleap-anipose1\lib\site-packages\sleap_anipose\triangulation.py", line 176, in triangulate
    [
  File "D:\anaconda\envs\sleap-anipose1\lib\site-packages\sleap_anipose\triangulation.py", line 177, in <listcomp>
    cgroup.triangulate_optim(
  File "D:\anaconda\envs\sleap-anipose1\lib\site-packages\aniposelib\cameras.py", line 1193, in triangulate_optim
    p3ds = self.triangulate(points_shaped, progress=init_progress)
  File "D:\anaconda\envs\sleap-anipose1\lib\site-packages\aniposelib\cameras.py", line 483, in triangulate
    new_points[cnum] = cam.undistort_points(sub)
  File "D:\anaconda\envs\sleap-anipose1\lib\site-packages\aniposelib\cameras.py", line 313, in undistort_points
    out = cv2.undistortPoints(points,
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\calib3d\src\undistort.dispatch.cpp:401: error: (-215:Assertion failed) CV_IS_MAT(_src) && CV_IS_MAT(_dst) && (_src->rows == 1 || _src->cols == 1) && (_dst->rows == 1 || _dst->cols == 1) && _src->cols + _src->rows - 1 == _dst->rows + _dst->cols - 1 && (CV_MAT_TYPE(_src->type) == CV_32FC2 || CV_MAT_TYPE(_src->type) == CV_64FC2) && (CV_MAT_TYPE(_dst->type) == CV_32FC2 || CV_MAT_TYPE(_dst->type) == CV_64FC2) in function 'cvUndistortPointsInternal'
![image](https://github.com/user-attachments/assets/f645ab63-587f-4de6-b9d9-0ef963ae26b6)
In addition, when I execute the pytest tests command, the following error occurs. Is there a relationship between the two?
![image](https://github.com/user-attachments/assets/ff51b4c7-421f-46a1-a69b-3778062afb60)

**Comment by wyclearnpy** [comment]
![image](https://github.com/user-attachments/assets/954c7a40-9afc-4428-a9a1-71fa79850e62)
Information about the first picture

**Comment by amandaa1359** [comment]
Hello,

Wondering if anyone's figured out how to solve this issue? I'm getting the same error.
